version: "3"

services:
  db:
    container_name: twitter_db_dev
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - twitter-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=twitter
      - MYSQL_USER=twitter
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  app:
    container_name: twitter_app_dev
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
    depends_on: ["db"]
  web:
    container_name: twitter_web_dev
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
    depends_on: ["app"]

volumes:
  twitter-db:
